# Production Docker Compose configuration
version: '3.8'

services:
  flip-clock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flip-clock-prod
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - flip-clock-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flip-clock-network:
    driver: bridge